version: "3.9"
services:
  dbpg:
    build:
      context: ./dbpg
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./dbpg/data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
    platform: linux/arm64
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
#     в самом контейнере отключил авторизацию для es
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - dbpg
      - elasticsearch
