version: "3.9"
services:
  dbpg:
    build:
      context: ./dbpg
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - dbpg
